<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJq6xrpl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJq6xrpl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJq6xrpl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJq6xrpl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJq6xrpl\appProdProjectContainer(array(
    'container.build_hash' => 'Jq6xrpl',
    'container.build_id' => 'b1d87478',
    'container.build_time' => 1536318720,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJq6xrpl');
