<?php
/* Smarty version 3.1.32, created on 2018-09-07 13:11:16
  from 'C:\xampp\htdocs\antares_web\admin\themes\default\css\overrides.css' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.32',
  'unifunc' => 'content_5b925cd48dbd39_75813060',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    'dbf1c992f8f619c4bbde1d6606e0c81d92febebe' => 
    array (
      0 => 'C:\\xampp\\htdocs\\antares_web\\admin\\themes\\default\\css\\overrides.css',
      1 => 1532446064,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_5b925cd48dbd39_75813060 (Smarty_Internal_Template $_smarty_tpl) {
?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }
}
